"""Initial migration - create all tables

Revision ID: 022c6e677fa9
Revises:
Create Date: 2026-01-17 13:43:53.063427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "022c6e677fa9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("post_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("merchant_name", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("subcategory", sa.String(length=100), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=True),
        sa.Column("recurring_group_id", sa.UUID(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("ai_categorized", sa.Boolean(), nullable=True),
        sa.Column("user_verified", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transactions_account_date",
        "transactions",
        ["account_id", sa.literal_column("transaction_date DESC")],
        unique=False,
    )
    op.create_index(
        "idx_transactions_date_desc",
        "transactions",
        [sa.literal_column("transaction_date DESC")],
        unique=False,
    )
    op.create_index(
        "idx_transactions_user_date",
        "transactions",
        ["user_id", sa.literal_column("transaction_date DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_account_id"), "transactions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_category"), "transactions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_merchant_name"),
        "transactions",
        ["merchant_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_transaction_date"),
        "transactions",
        ["transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    op.add_column(
        "accounts",
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column("accounts", "user_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "accounts",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "accounts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "accounts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index(op.f("idx_accounts_active"), table_name="accounts")
    op.drop_index(op.f("idx_accounts_type"), table_name="accounts")
    op.drop_index(op.f("idx_accounts_user_id"), table_name="accounts")
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.drop_column("accounts", "metadata")
    op.alter_column("budgets", "user_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "budgets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(
        op.f("budgets_user_id_category_subcategory_period_start_date_key"),
        "budgets",
        type_="unique",
    )
    op.drop_index(op.f("idx_budgets_active"), table_name="budgets")
    op.drop_index(op.f("idx_budgets_period"), table_name="budgets")
    op.drop_index(op.f("idx_budgets_user_id"), table_name="budgets")
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_user_budget",
        "budgets",
        ["user_id", "category", "subcategory", "period", "start_date"],
    )
    op.drop_table_comment(
        "budgets",
        existing_comment="User-defined spending budgets with alerts",
        schema=None,
    )
    op.alter_column(
        "categorization_rules", "user_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "categorization_rules",
        "pattern_value",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "categorization_rules",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(
        op.f("categorization_rules_user_id_pattern_type_pattern_value_key"),
        "categorization_rules",
        type_="unique",
    )
    op.drop_index(
        op.f("idx_categorization_rules_pattern"), table_name="categorization_rules"
    )
    op.drop_index(
        op.f("idx_categorization_rules_user"), table_name="categorization_rules"
    )
    op.create_index(
        op.f("ix_categorization_rules_user_id"),
        "categorization_rules",
        ["user_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_pattern",
        "categorization_rules",
        ["user_id", "pattern_type", "pattern_value"],
    )
    op.drop_table_comment(
        "categorization_rules",
        existing_comment="AI-learned rules for automatic transaction categorization",
        schema=None,
    )
    op.add_column("sync_jobs", sa.Column("stage", sa.String(length=50), nullable=True))
    op.add_column(
        "sync_jobs",
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "sync_jobs",
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column("sync_jobs", "user_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "sync_jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index(op.f("idx_sync_jobs_flow_run"), table_name="sync_jobs")
    op.drop_index(op.f("idx_sync_jobs_status"), table_name="sync_jobs")
    op.drop_index(op.f("idx_sync_jobs_type"), table_name="sync_jobs")
    op.drop_index(op.f("idx_sync_jobs_user_id"), table_name="sync_jobs")
    op.create_index(
        op.f("ix_sync_jobs_user_id"), "sync_jobs", ["user_id"], unique=False
    )
    op.drop_table_comment(
        "sync_jobs",
        existing_comment="Tracks Prefect workflow execution status",
        schema=None,
    )
    op.drop_column("sync_jobs", "metadata")
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.add_column(
        "sync_jobs",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table_comment(
        "sync_jobs",
        "Tracks Prefect workflow execution status",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_sync_jobs_user_id"), table_name="sync_jobs")
    op.create_index(
        op.f("idx_sync_jobs_user_id"), "sync_jobs", ["user_id"], unique=False
    )
    op.create_index(op.f("idx_sync_jobs_type"), "sync_jobs", ["job_type"], unique=False)
    op.create_index(op.f("idx_sync_jobs_status"), "sync_jobs", ["status"], unique=False)
    op.create_index(
        op.f("idx_sync_jobs_flow_run"),
        "sync_jobs",
        ["prefect_flow_run_id"],
        unique=False,
    )
    op.alter_column(
        "sync_jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column("sync_jobs", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("sync_jobs", "meta")
    op.drop_column("sync_jobs", "progress")
    op.drop_column("sync_jobs", "stage")
    op.create_table_comment(
        "categorization_rules",
        "AI-learned rules for automatic transaction categorization",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint("uq_user_pattern", "categorization_rules", type_="unique")
    op.drop_index(
        op.f("ix_categorization_rules_user_id"), table_name="categorization_rules"
    )
    op.create_index(
        op.f("idx_categorization_rules_user"),
        "categorization_rules",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_categorization_rules_pattern"),
        "categorization_rules",
        ["pattern_type", "pattern_value"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("categorization_rules_user_id_pattern_type_pattern_value_key"),
        "categorization_rules",
        ["user_id", "pattern_type", "pattern_value"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "categorization_rules",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "categorization_rules",
        "pattern_value",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "categorization_rules", "user_id", existing_type=sa.UUID(), nullable=True
    )
    op.create_table_comment(
        "budgets",
        "User-defined spending budgets with alerts",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint("uq_user_budget", "budgets", type_="unique")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.create_index(op.f("idx_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_budgets_period"), "budgets", ["period", "start_date"], unique=False
    )
    op.create_index(op.f("idx_budgets_active"), "budgets", ["is_active"], unique=False)
    op.create_unique_constraint(
        op.f("budgets_user_id_category_subcategory_period_start_date_key"),
        "budgets",
        ["user_id", "category", "subcategory", "period", "start_date"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "budgets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column("budgets", "user_id", existing_type=sa.UUID(), nullable=True)
    op.add_column(
        "accounts",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.create_index(op.f("idx_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_accounts_type"), "accounts", ["account_type"], unique=False
    )
    op.create_index(
        op.f("idx_accounts_active"), "accounts", ["is_active"], unique=False
    )
    op.alter_column(
        "accounts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "accounts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "accounts",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column("accounts", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("accounts", "meta")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_transaction_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_merchant_name"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_account_id"), table_name="transactions")
    op.drop_index("idx_transactions_user_date", table_name="transactions")
    op.drop_index("idx_transactions_date_desc", table_name="transactions")
    op.drop_index("idx_transactions_account_date", table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
